CREATE TABLE Traveller (
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESTINATION VARCHAR(255),
END_DATE TIMESTAMP(23,10),
NAME VARCHAR(255),
PASSWORD VARCHAR(255),
SOURCE VARCHAR(255),
START_DATE TIMESTAMP(23,10));
